src/Entity/Meeting.php
<?php

namespace App\Entity;

use DateTime;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\ORM\Event\LifecycleEventArgs;
use Doctrine\ORM\Event\PreUpdateEventArgs;
use Doctrine\ORM\Mapping as ORM;
use Gedmo\Mapping\Annotation as Gedmo;
use Gedmo\Timestampable\Traits\TimestampableEntity;
use JMS\Serializer\Annotation\Groups;
use Ramsey\Uuid\Uuid;
use Ramsey\Uuid\UuidInterface;
use OpenApi\Annotations as OA;
use JMS\Serializer\Annotation as Serializer;
use Symfony\Component\Validator\Constraints as Assert;


/**
 * Meeting
 *
 * @ORM\Entity(repositoryClass="App\Entity\MeetingRepository")
 * @ORM\Table(name="meeting")
 */
class Meeting
{

  use TimestampableEntity;

  const STATUS_PENDING = 0;
  const STATUS_APPROVED = 1;
  const STATUS_REFUSED = 2;
  const STATUS_MISSED = 3;
  const STATUS_DONE = 4;
  const STATUS_CANCELLED = 5;
  const STATUS_DRAFT = 6;

  /**
   * @ORM\Column(type="guid")
   * @ORM\Id
   * @OA\Property(description="Meeting's uuid", type="string")
   * @Groups({"read", "kafka"})
   */
  private $id;

  /**
 * @ORM\ManyToOne(targetEntity="App\Entity\Calendar")
 * @ORM\JoinColumn(name="calendar_id", referencedColumnName="id", nullable=false, onDelete="CASCADE")
 * @Assert\NotBlank(message="Questo campo è obbligatorio (calendar)")
 * @OA\Property(description="Meeting's calendar id", type="string")
 * @Groups({"kafka"})
 */
  private $calendar;

  /**
   * @ORM\ManyToOne(targetEntity="App\Entity\OpeningHour", inversedBy="meetings")
   * @ORM\JoinColumn(name="opening_hour_id", referencedColumnName="id", nullable=true)
   * @OA\Property(description="Meeting's opening hour id", type="string")
   * @Groups({"kafka"})
   */
  private $openingHour;

  /**
   * @var string
   *
   * @ORM\Column(name="email", type="string", length=255, nullable=true)
   * @OA\Property(description="Meeting's user email", type="string")
   * @Groups({"read", "write", "kafka"})
   */
  private $email;

  /**
   * @var string
   *
   * @ORM\Column(name="phone_number", type="string", nullable=true)
   * @OA\Property(description="Meeting's user phone number", type="string")
   * @Groups({"read", "write", "kafka"})
   */
  private $phoneNumber;

  /**
   * @var string
   *
   * @ORM\Column(name="fiscal_code", type="string", length=16, nullable=true)
   * @OA\Property(description="Meeting's user fiscal code", type="string")
   * @Groups({"read", "write", "kafka"})
   */
  private $fiscalCode;

  /**
   * @var string
   *
   * @ORM\Column(name="name", type="string", length=255, nullable=true)
   * @OA\Property(description="Meeting's user name", type="string")
   * @Groups({"read", "write", "kafka"})
   */
  private $name;

  /**
   * @ORM\ManyToOne(targetEntity="App\Entity\CPSUser")
   * @ORM\JoinColumn(name="user_id", referencedColumnName="id", nullable=true)
   * @OA\Property(description="Meeting's user id", type="string")
   * @Serializer\Exclude()
   */
  private $user;

  /**
   * @var \DateTime
   *
   * @ORM\Column(name="from_time", type="datetime")
   * @Assert\NotBlank(message="Questo campo è obbligatorio (from Time)")
   * @OA\Property(description="Meeting's from Time")
   * @Groups({"read", "write", "kafka"})
   */
  private $fromTime;

  /**
   * @var \DateTime
   *
   * @ORM\Column(name="to_time", type="datetime")
   * @Assert\NotBlank(message="Questo campo è obbligatorio (to Time)")
   * @OA\Property(description="Meeting's to Time")
   * @Groups({"read", "write", "kafka"})
   */
  private $toTime;

  /**
   * @var string
   *
   * @ORM\Column(name="user_message", type="text", nullable=true)
   * @OA\Property(description="Meeting's User Message", type="string")
   * @Groups({"read", "write", "kafka"})
   */
  private $userMessage;

  /**
   * @var string
   *
   * @ORM\Column(name="motivation_outcome", type="text", nullable=true)
   * @OA\Property(description="Meeting's Operator Message", type="string")
   * @Groups({"read", "write", "kafka"})
   */
  private $motivationOutcome;

  /**
   * @Serializer\Exclude()
   * @ORM\ManyToMany(targetEntity="App\Entity\Pratica", mappedBy="meetings")
   */
  private $applications;

  /**
   * @var string
   *
   * @ORM\Column(name="videoconference_link", type="string", nullable=true)
   * @Assert\Url(message="url non valido (videoconferenceLink)")
   * @OA\Property(description="Meeting's videoconference link", type="string")
   * @Groups({"read", "write", "kafka"})
   */
  private $videoconferenceLink;

  /**
   * @ORM\Column(type="integer")
   * @Assert\NotBlank(message="Seleziona un'opzione. Lo stato è un parametro obbligatorio")
   * @Assert\NotNull()
   * @OA\Property(description="Meeting's status", type="integer")
   * @Groups({"read", "write"})
   */
  private $status;

  /**
   * @ORM\Column(type="integer", nullable=false)
   * @OA\Property(description="Meeting's rescheduled times", type="integer")
   * @Groups({"read", "write", "kafka"})
   */
  private $rescheduled;

  /**
   * @var string
   *
   * @ORM\Column(name="cancel_link", type="string", length=255, nullable=true)
   * @OA\Property(description="Meeting's cancel link", type="string")
   * @Serializer\Exclude()
   */
  private $cancelLink;

  /**
   * @var \DateTime
   *
   * @ORM\Column(name="draft_expiration", type="datetime", nullable=true)
   * @OA\Property(description="Meeting draft expiration time")
   * @Groups({"read", "write", "kafka"})
   */
  private $draftExpiration;

  /**
   * @var \DateTime
   * @ORM\Column(type="date", nullable=true)
   * @OA\Property(description="First available date when meeting was created, format Y-m-d")
   * @Serializer\Type("DateTime<'Y-m-d'>")
   * @Groups({"read", "write", "kafka"})
   */
  private $firstAvailableDate;

  /**
   * @var \DateTime
   * @ORM\Column(type="time", nullable=true)
   * @OA\Property(description="First available end time")
   * @Serializer\Exclude()
   */
  private $firstAvailableStartTime;

  /**
   * @var \DateTime
   * @ORM\Column(type="time", nullable=true)
   * @OA\Property(description="First available end time")
   * @Serializer\Exclude()
   */
  private $firstAvailableEndTime;

  /**
   * @var \DateTime
   * @ORM\Column(type="datetime", nullable=true)
   * @OA\Property(description="Datetime when first availability was stored")
   * @Groups({"read", "write", "kafka"})
   */
  private $firstAvailabilityUpdatedAt;

  /**
   * @var \DateTime
   * @Gedmo\Timestampable(on="create")
   * @ORM\Column(type="datetime")
   * @Groups({"read", "kafka"})
   */
  protected $createdAt;

  /**
   * @var \DateTime
   * @Gedmo\Timestampable(on="update")
   * @ORM\Column(type="datetime")
   * @Groups({"read", "kafka"})
   */
  protected $updatedAt;

  /**
   * Meeting constructor.
   * @throws \Exception
   */

  public function __construct()
  {
    if (!$this->id) {
      $this->id = Uuid::uuid4();
      $this->cancelLink = hash('sha256', $this->id . (new DateTime())->format('c'));
      $this->applications = new ArrayCollection();
    }
  }

  /**
   * get id
   *
   * @return UuidInterface
   */
  public function getId()
  {
    return $this->id;
  }

  /**
   * Get Calendar
   *
   * @return Calendar
   */
  public function getCalendar(): ?Calendar
  {
    return $this->calendar;
  }

  /**
   * Set Calendar
   *
   * @param Calendar $calendar
   * @return $this
   */
  public function setCalendar(?Calendar $calendar): self
  {
    $this->calendar = $calendar;

    return $this;
  }

  /**
   * @Serializer\VirtualProperty()
   * @Serializer\Type("string")
   * @Serializer\SerializedName("calendar")
   * @Groups({"read", "write"})
   */
  public function getCalendarId(): string
  {
    return $this->calendar->getId();
  }

  /**
   * @Serializer\VirtualProperty()
   * @Serializer\Type("string")
   * @Serializer\SerializedName("application")
   * @Groups({"read", "write"})
   */
  public function getApplicationId(): ?string
  {
    $applicationId = null;
    if ($this->getApplications()->count() > 0) {
      $applicationId = $this->getApplications()->last()->getId();
    }
    return $applicationId;
  }

  /**
   * @Serializer\VirtualProperty()
   * @Serializer\Type("string")
   * @Serializer\SerializedName("application_id")
   * @Groups({"kafka"})
   */
  public function getApplicationIdKafka(): ?string
  {
    return $this->getApplicationId();
  }

  /**
   * @Serializer\VirtualProperty()
   * @Serializer\Type("string")
   * @Serializer\SerializedName("service_id")
   * @Groups({"kafka"})
   */
  public function getServiceId(): ?string
  {
    if ($this->getApplications()->count() > 0) {
      /** @var Pratica $application */
      $application = $this->getApplications()->last();
      return $application->getServizio()->getId();
    }
    return null;
  }

  /**
   * @Serializer\VirtualProperty()
   * @Serializer\Type("string")
   * @Serializer\SerializedName("user")
   * @Groups({"read", "write"})
   */
  public function getUserId(): ?string
  {
    if ($this->user){
      return $this->user->getId();
    }
    return null;
  }

  /**
   * @Serializer\VirtualProperty()
   * @Serializer\Type("string")
   * @Serializer\SerializedName("user_id")
   * @Groups({"kafka"})
   */
  public function getUserIdKafka(): ?string
  {
    if ($this->user){
      return $this->user->getId();
    }
    return null;
  }

  /**
   * @Serializer\VirtualProperty()
   * @Serializer\Type("string")
   * @Serializer\SerializedName("first_available_slot")
   * @Groups({"read", "write", "kafka"})
   */
  public function getFirstAvailableSlot()
  {
    if ($this->firstAvailableStartTime !== null && $this->firstAvailableEndTime !== null) {
      return $this->firstAvailableStartTime->format('H:i') . '-' . $this->firstAvailableEndTime->format('H:i');
    }
    return null;
  }

  /**
   * @Serializer\VirtualProperty()
   * @Serializer\Type("string")
   * @Serializer\SerializedName("status_name")
   * @Groups({"kafka"})
   */
  public function getStatusName()
  {
    $class = new \ReflectionClass(__CLASS__);
    $constants = $class->getConstants();

src/Form/Base/AllegatoType.php
<?php
namespace App\Form\Base;

use App\Entity\Allegato;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Vich\UploaderBundle\Form\Type\VichFileType;

/**
 * Class AllegatoType
 */
class AllegatoType extends AbstractType
{
    /**
     * @param FormBuilderInterface $builder
     * @param array                $options
     */
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        //TODO: add thumbnail if file has been submitted already
        //otherwise add file input
        $builder
            ->add('file', VichFileType::class, [
                'allow_delete' => false,
                'required' => true,
                'attr' => [
                    'class' => 'btn btn-default',
                ]
            ])
            ->add('description', TextType::class, [
                'required' => false,
            ]);
    }

    /**
     * @return string
     */
    public function getBlockPrefix()
    {
        return 'ocsdc_allegato';
    }

    /**
     * @param OptionsResolver $resolver
     */
    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults(array(
            'data_class' => Allegato::class,
        ));
    }
}

src/Form/TagsType.php
<?php

namespace App\Form;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\CallbackTransformer;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;

class TagsType extends AbstractType {

  public function buildForm(FormBuilderInterface $builder, array $options)
  {
    $builder->addViewTransformer(new CallbackTransformer(
      function ($original) {
        return $original ? implode(', ', $original) : '';
      },
      function ($submitted) {
        if (!$submitted) {
          return [];
        }

        $submitted = array_map(function($tag) {
          return trim($tag);
        }, explode(',', $submitted));

        return $submitted;
      }
    ));
  }

  public function getName()
  {
    return 'tags';
  }

  public function getParent()
  {
    return TextType::class;
  }


}

templates/Allegato/cpsUserCreateAllegato.html.twig
{% extends 'Default/index.html.twig' %}
{% block title %}{{ 'allegato.crea_allegato'|trans }} - Stanza del cittadino{% endblock %}

{% block main_content %}
    {% form_theme form 'form/ocsdc_form_style.html.twig' %}

    <div class="container-fluid">
        <div class="content">
            <div class="row">
                <div class="col-md-12">
                    <h1>{{ 'allegato.crea_allegato'|trans }}</h1>
                </div>
            </div>


            <div class="row">
                <div class="col-md-{% if form.vars.helper.guideText|length > 0 %}7{% else %}12{% endif %}">
                    <div class="row">
                        {{ form_start(form) }}
                        {{ form_errors(form) }}
                        <div>
                            {{ form.vars.helper.descriptionText|raw }}
                        </div>
                        {{ form_rest(form) }}
                        {{ form_end(form) }}
                    </div>
                </div>

                {% if form.vars.helper.guideText|length > 0 %}
                    <div class="col-md-4 col-md-offset-1 sidebar">
                        <h3><i class="fa fa-info" aria-hidden="true"></i> Info</h3>
                        <div class="alert alert-info" role="alert">
                            {{ form.vars.helper.guideText|raw }}
                        </div>
                    </div>
                {% endif %}
            </div>
        </div>
    </div>
{% endblock %}

templates/Allegato/cpsUserListAllegati.html.twig
{% extends 'Default/index.html.twig' %}
{% block title %}{{ 'operatori.allegati'|trans }} - Stanza del cittadino{% endblock %}

{% block main_content %}

    <section id="intro" class="container px-4 my-4">
        <div class="row">
            <div class="col-lg-12 px-lg-4 py-lg-2">

                <div class="row">
                    {% for item in allegati %}

                        {#{% if loop.index % 3 == 1 %}
                            <div class="row list">
                        {% endif %}#}

                        <div class="col-12 col-sm-6 col-lg-4" data-allegato="{{ item.allegato.id }}">

                            <article class="card-wrapper card-space">
                                <div class="card card-bg rounded shadow">
                                    <div class="card-body">
                                        <div class="category-top">
                                            <svg class="icon">
                                                <use xlink:href="/bootstrap-italia/dist/svg/sprite.svg#it-file"></use>
                                            </svg>
                                            <a class="category" href="#">{{ item.allegato.originalFilename }}</a>
                                        </div>
                                        <h5 class="card-title">
                                          {% if item.allegato.description == 'Allegato' %}
                                            {{ 'pratica.dettaglio.allegato.allegato' | trans }}
                                          {% else %}
                                              {{ item.allegato.description }}
                                          {% endif %}
                                        </h5>
                                        <p class="card-text">
                                            {% if item.allegato.pratiche | length > 0 %}
                                            <strong>{{ 'pratica.dettaglio.allegato.pratiche_list_intro'|trans }}</strong>
                                        <ul class="list-unstyled">
                                            {% for pratica in item.allegato.pratiche %}
                                                <li>
                                                    <a href="{{ path('pratiche_show', {'pratica': pratica}) }}">
                                                        <small>{{ pratica.servizio.name }}
                                                            ({{ ('pratica.dettaglio.stato_'~pratica.status)|trans }}
                                                            {% if pratica.statusName == 'STATUS_SUBMITTED' %}{{ pratica.submissionTime|date(ocsdc_default_date_format) }}{% else %}{{ pratica.creationTime|date(ocsdc_default_date_format) }}{% endif %}
                                                            )
                                                        </small>
                                                    </a>
                                                </li>
                                            {% endfor %}
                                        </ul>
                                        {% endif %}
                                        </p>

                                        <div class="row">
                                            <div class="col-6">
                                                <a href="{{ path( 'allegati_download_cpsuser', {'allegato': item.allegato.id}) }}"
                                                   class="btn btn-xs btn-info">{{ 'allegato.scarica_allegato'|trans }}</a>
                                            </div>
                                            <div class="col-6">
                                                <div class="pull-right">
                                                    {% if item.deleteform %}
                                                        {{ form(item.deleteform) }}
                                                    {% endif %}
                                                </div>
                                            </div>
                                        </div>

                                    </div>
                                </div>
                            </article>


                            {#<article class="panel panel-default servizio">
                                <div class="panel-body">
                                    <div data-title="{{ 'pratica.dettaglio.allegato.file'|trans }}">
                                        <strong>{{ 'pratica.dettaglio.allegato.file'|trans }}</strong>
                                        {{ item.allegato.originalFilename }}
                                    </div>
                                    <div data-title="{{ 'pratica.dettaglio.allegato.descrizione'|trans }}">
                                        <strong>{{ 'pratica.dettaglio.allegato.descrizione'|trans }}</strong>
                                        {{ item.allegato.description }}
                                    </div>
                                </div>
                            </article>#}
                        </div>

                        {#{% if (loop.index % 3 == 0 or loop.last) %}
                            </div>
                        {% endif %}#}

                    {% endfor %}
                </div>
            </div>
        </div>
    </section>

{% endblock %}